name: Build Ghidra ARM64 Decompiler

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    name: Build Decompiler for ARM64 (Linux)

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up QEMU and cross-compile toolchain
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake git gradle gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Clone Ghidra source
        run: |
          git clone https://github.com/NationalSecurityAgency/ghidra.git
          cd ghidra
          git submodule update --init --recursive

      - name: Build native ARM64 decompiler
        working-directory: ghidra
        run: |
          export CC=aarch64-linux-gnu-gcc
          export CXX=aarch64-linux-gnu-g++
          ./gradlew buildNatives_linux_arm_64 --stacktrace

      - name: List output
        working-directory: ghidra
        run: |
          find ./ -type f -name "decompile" || echo "No binary found"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ghidra-decompiler-arm64
          path: ghidra/build/os/linux_arm_64/decompile
