name: Build Android ARM64 Native Hook

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # Dùng NDK có sẵn trong máy ảo Ubuntu của GitHub
    - name: Locate and Export Android NDK
      run: |
        echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle" >> $GITHUB_ENV
        if [ -d "$ANDROID_HOME/ndk" ]; then
          LATEST_NDK=$(ls -r $ANDROID_HOME/ndk | head -n 1)
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/$LATEST_NDK" >> $GITHUB_ENV
        fi

    # Tải xdl và bộ Dobby Pre-built
    - name: Download Dependencies
      run: |
        echo "[*] Cleaning old directories..."
        rm -rf dobby_prebuilt xdl
        
        echo "[*] Downloading xdl (Linker Extension)..."
        git clone --depth=1 https://github.com/hexhacking/xdl.git xdl

        echo "[*] Downloading Pre-built Dobby..."
        mkdir -p dobby_prebuilt
        curl -L https://raw.githubusercontent.com/jmpews/Dobby/master/include/dobby.h -o dobby_prebuilt/dobby.h
        curl -L https://github.com/jmpews/Dobby/releases/download/v1.2.0/libdobby.a -o dobby_prebuilt/libdobby.a

    # Tự động quét tìm vị trí độc lập của xdl.c và xdl.h
    - name: Locate XDL Files Dynamically
      run: |
        XDL_FILE_PATH=$(find $(pwd)/xdl -name "xdl.c" | head -n 1)
        XDL_H_PATH=$(find $(pwd)/xdl -name "xdl.h" | head -n 1)
        XDL_DIR_INC=$(dirname "$XDL_H_PATH")
        
        echo "REAL_XDL_SRC=$XDL_FILE_PATH" >> $GITHUB_ENV
        echo "REAL_XDL_INC=$XDL_DIR_INC" >> $GITHUB_ENV
        
        echo "[+] Found xdl.c at: $XDL_FILE_PATH"
        echo "[+] Found xdl.h directory at: $XDL_DIR_INC"

    # Biên dịch thẳng file .so
    - name: Build Main Hook Library
      run: |
        mkdir -p build && cd build
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=android-24 \
          -DDT_XDL_SRC="$REAL_XDL_SRC" \
          -DDT_XDL_INC="$REAL_XDL_INC" \
          -DCMAKE_BUILD_TYPE=Release
        make -j$(nproc)

    - name: Upload Output Library (.so)
      uses: actions/upload-artifact@v4
      with:
        name: libebpf_helper-arm64
        path: build/libebpf_helper.so
