name: Build Ghidra ARM64 Decompiler

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Ghidra source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Java 17 (required by Ghidra)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Disable Windows-only Debugger modules
        run: |
          echo ">>> Disabling Windows-only Debugger modules..."
          sed -i '/Debugger-agent-dbgeng/d' Ghidra/settings.gradle
          sed -i '/Debugger-agent-dbgmodel/d' Ghidra/settings.gradle
          sed -i '/Debugger-agent-dbgmodel-dbgeng/d' Ghidra/settings.gradle

      - name: Build ARM64 Decompiler only
        run: |
          echo ">>> Building Ghidra ARM64 Decompiler..."
          ./gradlew --no-daemon --parallel :Ghidra:Processors:ARM:build

      - name: Build SLEIGH ARM64 decompiler processor
        run: |
          echo ">>> Building SLEIGH ARM64 Processor..."
          ./gradlew --no-daemon :Ghidra:Processors:ARM:sleighCompile

      - name: Assemble Ghidra ARM64 modules
        run: |
          ./gradlew --no-daemon :Ghidra:Processors:ARM:assemble

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ghidra-arm64-processor
          path: |
            Ghidra/Processors/ARM/build/distributions/
            Ghidra/Processors/ARM/build/libs/
