name: Build Ghidra Decompiler ARM64

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full Ghidra source
        run: |
          git clone --recursive https://github.com/NationalSecurityAgency/ghidra.git
          cd ghidra
          git submodule update --init --recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            openjdk-21-jdk unzip

      - name: Verify Java
        run: java -version

      - name: Prepare local Maven repo
        working-directory: ghidra
        run: |
          mkdir -p ghidra_dependencies/flatRepo
          echo "flatRepo=ghidra_dependencies/flatRepo" > ghidra.repos.config

      - name: Build native ARM64 Decompiler
        working-directory: ghidra
        run: |
          export CC=aarch64-linux-gnu-gcc
          export CXX=aarch64-linux-gnu-g++
          ./gradlew --no-daemon buildNatives_linux_arm_64 --stacktrace --info

      - name: List build outputs
        working-directory: ghidra
        run: |
          echo "✅ Build complete. Listing decompiler files:"
          ls -R build/os/linux_arm_64 || true

      - name: Upload ARM64 Decompiler
        uses: actions/upload-artifact@v4
        with:
          name: ghidra-decompiler-arm64
          path: ghidra/build/os/linux_arm_64/
