name: Build ARM64 Decompiler

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Tự động tải mã nguồn từ repository chính thức của Ghidra
      - name: Checkout Ghidra source code
        uses: actions/checkout@v3
        with:
          repository: NationalSecurityAgency/ghidra
          ref: master  # Sử dụng branch master, thay đổi nếu cần phiên bản cụ thể
          path: ghidra-source

      # Cài đặt Java 21 (yêu cầu của Ghidra 11.4.2)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Cài đặt công cụ build và cross-compiler cho ARM64
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      # Build decompiler
      - name: Build ARM64 decompiler
        run: |
          mkdir -p build bin
          cd ghidra-source/Ghidra/Features/Decompiler/src/decompile/cpp
          make CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ ARCH=arm64
          mv decompile ../../../build/

      # Kiểm tra kết quả
      - name: Verify build
        run: |
          ls -lh build/decompile
          file build/decompile

      # Tải artifact lên (tùy chọn)
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: arm64-decompile
          path: build/decompile
