name: Build Ghidra ARM64 Decompiler

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Detect Ghidra root path
        id: detect
        run: |
          if [ -f settings.gradle ]; then
            echo "root=." >> $GITHUB_OUTPUT
          elif [ -f Ghidra/settings.gradle ]; then
            echo "root=Ghidra" >> $GITHUB_OUTPUT
          else
            echo "❌ Không tìm thấy settings.gradle"
            ls -R | head -50
            exit 1
          fi

      - name: Disable Windows-only Debugger modules
        run: |
          GHIDRA_ROOT="${{ steps.detect.outputs.root }}"
          echo "Ghidra root detected: $GHIDRA_ROOT"
          sed -i '/Debugger-agent-dbgeng/d' "$GHIDRA_ROOT/settings.gradle" || true
          sed -i '/Debugger-agent-dbgmodel/d' "$GHIDRA_ROOT/settings.gradle" || true
          sed -i '/Debugger-agent-dbgmodel-dbgeng/d' "$GHIDRA_ROOT/settings.gradle" || true

      - name: Build ARM64 Decompiler only
        run: |
          GHIDRA_ROOT="${{ steps.detect.outputs.root }}"
          cd "$GHIDRA_ROOT"
          ./gradlew --no-daemon --parallel :Processors:ARM:build

      - name: Build ARM64 sleigh
        run: |
          GHIDRA_ROOT="${{ steps.detect.outputs.root }}"
          cd "$GHIDRA_ROOT"
          ./gradlew --no-daemon :Processors:ARM:sleighCompile

      - name: Assemble ARM64
        run: |
          GHIDRA_ROOT="${{ steps.detect.outputs.root }}"
          cd "$GHIDRA_ROOT"
          ./gradlew --no-daemon :Processors:ARM:assemble

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ghidra-arm64-build
          path: |
            **/Processors/ARM/build/distributions/**
            **/Processors/ARM/build/libs/**
