name: Build Ghidra ARM64 Decompiler

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          repository: NationalSecurityAgency/ghidra
          submodules: recursive

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            openjdk-21-jdk unzip

      - name: Verify Java version
        run: java -version

      - name: Prepare local Maven repo
        run: |
          mkdir -p ghidra_dependencies/flatRepo
          echo "flatRepo=ghidra_dependencies/flatRepo" > ghidra.repos.config

      - name: Build native ARM64 decompiler
        run: |
          export CC=aarch64-linux-gnu-gcc
          export CXX=aarch64-linux-gnu-g++
          ./gradlew --no-daemon buildNatives_linux_arm_64 --stacktrace --info

      - name: Package build artifacts
        run: |
          mkdir -p output
          cp -r build/os/linux_arm_64 output/
          ls -R output

      - name: Upload decompiler binary
        uses: actions/upload-artifact@v4
        with:
          name: ghidra-arm64-decompiler
          path: output/
